### ISSUE TITLE
Stage-in/out was executed on the master node.

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#1]
## Environment

Nodes:
- Master node (Job scheduler was running.)
- Lustre client nodes(LoD would be built on these nodes.)

My Slurm's commit ID: 4d00faf8f3bc8828cb57838b91ac485d15fec2f9

## Issue

I tried to do stage-in/out with LoD plugin.

I expected that target file would be staged in a LoD on Lustre client nodes.
But target file was staged in the master(Job Scheduler) node.

This is the my job script for testing.
```
#!/bin/bash

#LOD setup
#LOD stage_in source=/mnt/lustre/test.txt destination=/lod/test.txt
#LOD stop
#SBATCH --job-name=test
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=test-%j.out

cat /lod/test.txt
echo "end" 
```

* "/mnt/lustre" is a global storage mountpoint(lustre).
* "/lod" is a local storage(Lustre on demand).

After all, test.txt was staged in "/lod" directory on the master node.
And, stage-out was also executed on the master node.

**Comment by KnightKu** [comment]
This issue should be fixed at commit [0b1a2c](https://github.com/DDNStorage/slurm/commit/0b1a2cad2d713a3a2b5526828032d976566160b1), 
please checkout and try again, thanks.

**Comment by rkmrHonjo** [comment]
OK, I try it after that.

**Comment by rkmrHonjo** [comment]
@KnightKu 
I tried commit 0b1a2cad2d713a3a2b5526828032d976566160b1 .

As a result, that version requires `--node` option to lod start.
But, the following lod package isn't implemented `--node` option.

https://woscloud.datadirectnet.jp/index.php/s/Ppdx4EehL0rg62N

Is there a newer version lod?

**Comment by KnightKu** [comment]
@rkmrHonjo 
Ah, yeah, it's out of date, I'll share you the latest lod package later (following the comment)

**Comment by rkmrHonjo** [comment]
@KnightKu 
> Ah, yeah, it's out of date, I'll share you the latest lod package later (following the comment)

Thanks. I'm waiting for it.

**Comment by rkmrHonjo** [comment]
@KnightKu 
Excuse me, is the lod updated in a few days?
It looks that lod is not updated yet.

**Comment by rkmrHonjo** [comment]
@KnightKu 
I confirmed that this issue was fixed in https://github.com/DDNStorage/slurm/commit/0b1a2cad2d713a3a2b5526828032d976566160b1 . Thanks a lot!

**Comment by KnightKu** [comment]
@rkmrHonjo, NP:)
