### ISSUE TITLE
[Request] Improve the timing of stage-in

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#2]
In datawarp plugin, the stage-in logic is implemented in bb_p_job_try_stage_in() function. But LoD plugin implements it in bb_p_job_begin() function.

I think that bb_p_job_try_stage_in() is better than bb_p_job_begin(). Because bb_p_job_try_stage_in() can start stage-in while the job is waiting.

**Comment by KnightKu** [comment]
> I think that bb_p_job_try_stage_in() is better than bb_p_job_begin(). Because bb_p_job_try_stage_in() can start stage-in while the job is waiting.

Yeah, true, there's a WIP patch to rework the workflow to make routines more rational, will push it once  done, thanks.

**Comment by rkmrHonjo** [comment]
Thanks a lot. I wait for it.

**Comment by KnightKu** [comment]
It's available  since commit 0a5419d now.

**Comment by rkmrHonjo** [comment]
Thanks.
I try with the commit.

**Comment by KnightKu** [comment]
Hi @rkmrHonjo ,
any luck there?

**Comment by rkmrHonjo** [comment]
@KnightKu 
https://github.com/DDNStorage/slurm/commit/0a5419d44c6ff49aea7367b0d7f4cc108d2c7354 is OK.
Thanks a lot.
