### ISSUE TITLE
LOD setup process is able to run without #LOD setup directive.

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#3]
I tried to do stage_in without #LOD setup directive by mistake.
However, LOD setup process looked like it was done.

This is probably the correct script.

* job script (with #LOD setup)
```
#!/bin/bash

#LOD setup
#LOD stage_in source=/mnt/lustre/test.txt destination=/lod/test.txt
#SBATCH --job-name=test
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=test-%j.out

cat /lod/test.txt
echo "end" 
```

This is the script I used:

* job script without #LOD setup by mistake
```
#!/bin/bash

#LOD stage_in source=/mnt/lustre/test.txt destination=/lod/test.txt
#SBATCH --job-name=test
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=test-%j.out

cat /lod/test.txt
echo "end" 
```

* slurmctld.log of the script without #LOD setup:

```
[2019-07-01T02:06:42.957] debug2: RDEBUG: command:
[2019-07-01T02:06:42.957] debug2: lod
[2019-07-01T02:06:42.957] debug2: start
[2019-07-01T02:06:42.957] debug2: RDEBUG: bb_p_job_begin lod_setup rc=[]
```

**Comment by KnightKu** [comment]
yeah, it's a problem now, previously the validation check is rough, it doesn't check whether LOD instance was setup or not when do stage-in/stage-out, should be fix in next patch (big change), thanks.

**Comment by rkmrHonjo** [comment]
Thanks a lot. I wait for it.

**Comment by KnightKu** [comment]
Also, it's fixed under commit 0a5419d, please checkout and try with it.

**Comment by rkmrHonjo** [comment]
Thanks.
I try with the commit.

**Comment by rkmrHonjo** [comment]
I confirmed that this issue was fixed in https://github.com/DDNStorage/slurm/commit/0a5419d44c6ff49aea7367b0d7f4cc108d2c7354 .

Thanks a lot!
