### ISSUE TITLE
[Request]Validate the options

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#5]
Validations for the options are not implemented in the current bb_p_job_validate(). I think this is unkind.

For example, "source" option and "destination" option are required for "#LOD stage_in". But current LoD plugin doesn't confirm it.

**Comment by KnightKu** [comment]
yeah, it's missing now, but options validation will be introduced in the upcoming patch.

**Comment by rkmrHonjo** [comment]
Thanks a lot. I wait for it.

**Comment by KnightKu** [comment]
commit 0a5419d introduced the validation support.

**Comment by rkmrHonjo** [comment]
Thanks.
I confirm the commit.

**Comment by rkmrHonjo** [comment]
@KnightKu 
I confirmed that this issue was fixed in https://github.com/DDNStorage/slurm/commit/0a5419d44c6ff49aea7367b0d7f4cc108d2c7354 .

Thanks a lot!
