### ISSUE TITLE
Specified options of the previous job inherited to the next job.

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#6]
I ran the following jobs.

1. A job with a correct script.
2. A job with a incorrect script. Stage_in options were not specified in this script by mistake.

As a result, the second job inherited the options of the first job.

This is 1st job's script.
Options for "#LOD stage_in" are specified.

```
#!/bin/bash

#LOD setup
#LOD stage_in source=/mnt/lustre/test.txt destination=/lod/test.txt
#LOD stop
#SBATCH --job-name=test
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=test-%j.out

cat /lod/test.txt
echo "end" 
```

This is 2nd job's script.
Options for "#LOD stage_in" are not specified by mistake.
But stage-in read from /mnt/lustre/test.txt and copied to /lod/test.txt.

```
#!/bin/bash

#LOD setup
#LOD stage_in
#LOD stop
#SBATCH --job-name=test
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=test-%j.out

cat /lod/test.txt
echo "end" 
```

**Comment by KnightKu** [comment]
Hmm...which head/commit did you try with? this issue should have been fixed since commit [0b1a2cad](https://github.com/DDNStorage/slurm/commit/0b1a2cad2d713a3a2b5526828032d976566160b1)
so if you were trying with older one, please checkout latest and try again, thanks.

**Comment by rkmrHonjo** [comment]
@KnightKu 
I used commit 4d00faf8f3bc8828cb57838b91ac485d15fec2f9 .

**Comment by KnightKu** [comment]
I see, it's a bit old. this issue should be fixed since commit 0b1a2cad, but for better,  please checkout latest head (commit 0a5419d).

**Comment by rkmrHonjo** [comment]
OK, I confirm the latest head.

**Comment by rkmrHonjo** [comment]
@KnightKu 
I confirmed that this issue was fixed in the latest head (commit https://github.com/DDNStorage/slurm/commit/0a5419d44c6ff49aea7367b0d7f4cc108d2c7354 ).

Thanks a lot!
