### ISSUE TITLE
LOD stop doesn't work without LOD stage_out

### ISSUE THREAD

**Issue by rkmrHonjo** [DDNStorage/slurm#7]
# Target Commit
- 0a5419d

# Issue

\#LOD stop doesn't work if #LOD stage_out is not run.
In my understanding, LOD is able to stop even if #LOD stage_out is not run.

## Examples of job script

\#LOD stop works correctly in the following job script.
\#LOD stage_out is defined before \#LOD stop.

- jobscript (with stage out)
    ```
    #!/bin/bash

    #SBATCH --job-name=test
    #SBATCH --partition=debug
    #SBATCH --output=test-stop-%j.out
    #SBATCH --nodelist=lod-node1
    #LOD setup
    #LOD stage_in --source=/mnt/lustre/test_stop/ --destination=/lod/
    #LOD stage_out --source=/lod/ --destination=/mnt/lustre/test_stop/stage_out/
    #LOD stop

    echo "test_stop" 
    ls -al /lod/
    ```

However, the following job script did not run #LOD stop processing.
\#LOD stage_out is not defined in this script.

- jobscript (without stage out)
    ```
    #!/bin/bash

    #SBATCH --job-name=test
    #SBATCH --partition=debug
    #SBATCH --output=test-stop-%j.out
    #SBATCH --nodelist=lod-node1
    #LOD setup
    #LOD stage_in --source=/mnt/lustre/test_stop/ --destination=/lod/
    #LOD stop

    echo "test_stop" 
    ls -al /lod/
    ```
The job status after running the above script is this:
```
[root@lod-master issue]# squeue
JOBID  PARTITION      USER  ST        TIME   NODES NODELIST(REASON)
    7      debug      root  SO        0:00       1 (burst_buffer/lod: Stage-out in progress)

[root@lod-master issue]# scancel 7

[root@lod-master issue]# squeue
JOBID  PARTITION      USER  ST        TIME   NODES NODELIST(REASON)
    7      debug      root  SO        0:00       1 (burst_buffer/lod: Stage-out in progress)
```

P.S.
Cancel operation is not accepted if #LOD stage_out is not defined.
This is the slurmctld.log when I cancelled.
```
[2019-08-02T04:07:10.109] _slurm_rpc_kill_job: REQUEST_KILL_JOB JobId=7 uid 0
[2019-08-02T04:07:10.109] debug2: _slurm_rpc_kill_job: job_str_signal() JobId=7 sig 9 returned Job/step already completing or completed
```

**Comment by KnightKu** [comment]
Hi @rkmrHonjo ,
Thanks for reporting this.
Trying to reproduce it now, and will look into it then.

**Comment by KnightKu** [comment]
fixed under commit 6d54185
Please checkout and try with it, thanks.

**Comment by rkmrHonjo** [comment]
@KnightKu 
Thanks a lot!
I retry with it.

**Comment by rkmrHonjo** [comment]
@KnightKu 
Thanks, your fix works correctly.
I close this issue.
